version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "6969:6969"  # Port mà Laravel backend sẽ chạy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"  # Port mà Vue.js frontend sẽ chạy
